version: "3.7"
services:
  server:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8082:8082"
    command: ["sh", "-c", "/app/bin/migrate up && /app/bin/api"]

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: banner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: